### PR TITLE
Add script to install sty files

### PR DESCRIPTION
**Pull request by andrewzgu**

### CODE REVIEW

**Comment by andrewzgu** [comment]
Maybe we could put this step directly in `init.sh`?

**Comment by vEnhance** [comment]
> Maybe we could put this step directly in `init.sh`?

I dunno how much I want to do this because you only need to install sty files once, rather than every TST cycle

**Comment by vEnhance** [comment]
How does that look? We can merge if that looks OK.

**Comment by andrewzgu** [comment]
Just added a small change to README since installing jinja is also a once per computer thing. Seems good to me now.

**Pull request merged**
